# Generated by Django 3.2 on 2025-01-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='readdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
