# Generated by Django 3.2 on 2025-01-23 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='purchasedate',
            new_name='purchase_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='readdate',
            new_name='read_date',
        ),
    ]
